language: python
language: bash
python:
  - "3.6.3"

sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.20.1
  DOCKER_VERSION: 18.03.0
  ENVIRONMENT: travis

services:
  - docker


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get -y install tree python3-pip
  - sudo python3 -m easy_install pyyaml
  - make build
install:
  - ENVIRONMENT=travis make dctest

script:
  ENVIRONMENT=travis docker ps
